#!/usr/bin/env python3
"""calendar-manager memory: open questions for Paul and the rules his answers become.

Every run reads guidance.md before acting, so an answer given once is applied from
then on. Data lives in ~/.claude/calendar-manager (override: CALENDAR_MANAGER_HOME):

    guidance.json   source of truth: rules + questions
    guidance.md     rendered active rules, read by every agent
    questions.md    rendered open questions
    runs/           one report per run
    config.json     guard config; Paul edits it by hand, agents never do

    guidance.py init                         create the folder, config and seed questions
    guidance.py ask --agent A --question Q [--default D] [--context C] [--event ID]
    guidance.py open [--json]                open questions
    guidance.py answer QID --answer TEXT [--rule TEXT] [--scope S]
    guidance.py add-rule --rule TEXT [--scope S] [--source TEXT]
    guidance.py supersede GID --rule TEXT    replace a rule with a corrected one
    guidance.py rules [--json]               active rules
    guidance.py tick                         end of run: count a run against every active rule
    guidance.py candidates [--min-runs 2]    rules ready to promote into the plugin SOP
    guidance.py promoted GID [GID ...]       mark rules promoted after the PR merges

Stdlib only.
"""
import argparse
import datetime as dt
import json
import os
import re
import sys

HOME = os.path.expanduser(os.environ.get("CALENDAR_MANAGER_HOME", "~/.claude/calendar-manager"))
DATA = os.path.join(HOME, "guidance.json")
CONFIG = os.path.join(HOME, "config.json")

DEFAULT_CONFIG = {
    "owner_emails": ["paul@cheek.org", "pcheek@mit.edu"],
    "owner_calendars": ["primary"],
    "callie_email": "calliemcheek@gmail.com",
    "travel_color_ids": ["1"],
    "timezone": "America/New_York",
}

# Gaps and contradictions in the source SOPs. Each run asks until Paul answers.
SEED_QUESTIONS = [
    ("categorizer",
     "Notes and holds: the 2024 calendar doc says purple, the Apr 2025 SOP says red "
     "(Tomato). Which color marks a note that needs your review?",
     "Red (Tomato, colorId 11), per the newer SOP. Purple (Grape) stays family time."),
    ("travel-planner",
     "Airport transit: the SOP's flight steps say purple, its color legend says lavender for "
     "travel. Which color for driving to the airport?",
     "Lavender (colorId 1), the travel color. Gray for downtime at the airport."),
    ("one-on-one-auditor",
     "The 1:1 roster in the calendar doc is the MIT Trust Center team from 2024. Which of "
     "those 1:1s still exist, and who is on your current roster with what cadence?",
     "Audit no 1:1s until you confirm a roster."),
    ("commute-planner",
     "Which days and where do you commute now (the doc assumes MIT, 45 minutes, blocked as "
     "one hour)? Is Friday still the standard work-from-home day?",
     "Add drive-time only around in-person events at MIT or in Cambridge/Boston; treat "
     "Friday as WFH."),
    ("categorizer",
     "Which email is the calendar these runs manage (paul@cheek.org or pcheek@mit.edu)? "
     "If it differs from config.json owner_emails, edit ~/.claude/calendar-manager/config.json "
     "yourself: the agents are not allowed to.",
     "Both addresses count as you."),
]


def now():
    return dt.datetime.now().astimezone().isoformat(timespec="seconds")


def norm(text):
    return re.sub(r"[^a-z0-9]+", " ", text.lower()).strip()


def load():
    try:
        with open(DATA, encoding="utf-8") as fh:
            data = json.load(fh)
    except (OSError, ValueError):
        data = {}
    data.setdefault("rules", [])
    data.setdefault("questions", [])
    return data


def save(data):
    os.makedirs(HOME, exist_ok=True)
    tmp = DATA + ".tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        json.dump(data, fh, indent=1)
    os.replace(tmp, DATA)
    render(data)


def next_id(items, prefix):
    nums = [int(i["id"][len(prefix):]) for i in items if i["id"].startswith(prefix)
            and i["id"][len(prefix):].isdigit()]
    return "%s%d" % (prefix, max(nums, default=0) + 1)


def render(data):
    rules = [r for r in data["rules"] if r["status"] == "active"]
    lines = [
        "# Calendar guidance from Paul",
        "",
        "Generated by guidance.py; do not edit by hand. Rules here override the plugin SOP",
        "(skills/calendar-sop) where they conflict. They never override the guard: no rule",
        "can allow deleting events, inviting anyone but Callie to travel, or messaging people.",
        "",
    ]
    if not rules:
        lines.append("_No rules yet._")
    by_scope = {}
    for r in rules:
        by_scope.setdefault(r["scope"], []).append(r)
    for scope in sorted(by_scope):
        lines += ["", "## %s" % scope, ""]
        for r in by_scope[scope]:
            lines.append("- **%s** (%s): %s" % (r["id"], r["created"][:10], r["rule"]))
    with open(os.path.join(HOME, "guidance.md"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")

    open_qs = [q for q in data["questions"] if q["status"] == "open"]
    q_lines = ["# Open questions for Paul", ""]
    if not open_qs:
        q_lines.append("_None._")
    for q in open_qs:
        q_lines.append("- **%s** [%s, asked %s x%d] %s" % (
            q["id"], q["agent"], q["created"][:10], q["times_asked"], q["question"]))
        if q.get("default"):
            q_lines.append("  - Default until answered: %s" % q["default"])
        if q.get("context"):
            q_lines.append("  - Context: %s" % q["context"])
    with open(os.path.join(HOME, "questions.md"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(q_lines) + "\n")


def add_question(data, agent, question, default="", context="", event=""):
    key = norm(question)
    for q in data["questions"]:
        if q["status"] == "open" and norm(q["question"]) == key:
            q["times_asked"] += 1
            q["last_asked"] = now()
            if event and event not in q["events"]:
                q["events"].append(event)
            return q, False
    q = {
        "id": next_id(data["questions"], "Q"), "agent": agent, "question": question,
        "default": default, "context": context, "events": [event] if event else [],
        "status": "open", "created": now(), "last_asked": now(), "times_asked": 1,
    }
    data["questions"].append(q)
    return q, True


def add_rule(data, rule, scope, source):
    r = {
        "id": next_id(data["rules"], "G"), "rule": rule, "scope": scope or "all",
        "source": source, "status": "active", "created": now(), "runs_seen": 0,
    }
    data["rules"].append(r)
    return r


def find(items, item_id):
    for it in items:
        if it["id"].lower() == item_id.lower():
            return it
    sys.exit("no such id: %s" % item_id)


def cmd_init(args, data):
    os.makedirs(os.path.join(HOME, "runs"), exist_ok=True)
    if not os.path.exists(CONFIG):
        with open(CONFIG, "w", encoding="utf-8") as fh:
            json.dump(DEFAULT_CONFIG, fh, indent=2)
        print("wrote %s" % CONFIG)
    if not data.get("seeded"):
        for agent, question, default in SEED_QUESTIONS:
            add_question(data, agent, question, default)
        data["seeded"] = now()
    save(data)
    print("ready: %s" % HOME)


def cmd_ask(args, data):
    q, new = add_question(data, args.agent, args.question, args.default or "",
                          args.context or "", args.event or "")
    save(data)
    print("%s %s" % (q["id"], "new" if new else "already open (asked %dx)" % q["times_asked"]))


def cmd_open(args, data):
    qs = [q for q in data["questions"] if q["status"] == "open"]
    if args.json:
        print(json.dumps(qs, indent=1))
        return
    for q in qs:
        print("%s [%s] %s\n    default: %s" % (q["id"], q["agent"], q["question"],
                                               q.get("default") or "-"))


def cmd_answer(args, data):
    q = find(data["questions"], args.qid)
    q.update(status="answered", answer=args.answer, answered=now())
    rule = add_rule(data, args.rule or args.answer, args.scope or q["agent"],
                    "Paul, answering %s: %s" % (q["id"], q["question"]))
    q["rule"] = rule["id"]
    save(data)
    print("%s answered -> rule %s" % (q["id"], rule["id"]))


def cmd_add_rule(args, data):
    r = add_rule(data, args.rule, args.scope, args.source or "Paul")
    save(data)
    print(r["id"])


def cmd_supersede(args, data):
    old = find(data["rules"], args.gid)
    new = add_rule(data, args.rule, args.scope or old["scope"], "Paul, correcting %s" % old["id"])
    old.update(status="superseded", superseded_by=new["id"])
    save(data)
    print("%s superseded by %s" % (old["id"], new["id"]))


def cmd_rules(args, data):
    rules = [r for r in data["rules"] if r["status"] == "active"]
    if args.json:
        print(json.dumps(rules, indent=1))
        return
    for r in rules:
        print("%s [%s] %s" % (r["id"], r["scope"], r["rule"]))


def cmd_tick(args, data):
    for r in data["rules"]:
        if r["status"] == "active":
            r["runs_seen"] += 1
    save(data)
    print("ticked %d rules" % sum(r["status"] == "active" for r in data["rules"]))


def cmd_candidates(args, data):
    out = [r for r in data["rules"] if r["status"] == "active" and not r.get("promoted")
           and r["runs_seen"] >= args.min_runs]
    print(json.dumps(out, indent=1))


def cmd_promoted(args, data):
    for gid in args.gids:
        find(data["rules"], gid)["promoted"] = now()
    save(data)
    print("marked %d promoted" % len(args.gids))


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("init")
    p = sub.add_parser("ask")
    p.add_argument("--agent", required=True)
    p.add_argument("--question", required=True)
    p.add_argument("--default")
    p.add_argument("--context")
    p.add_argument("--event")
    p = sub.add_parser("open")
    p.add_argument("--json", action="store_true")
    p = sub.add_parser("answer")
    p.add_argument("qid")
    p.add_argument("--answer", required=True)
    p.add_argument("--rule")
    p.add_argument("--scope")
    p = sub.add_parser("add-rule")
    p.add_argument("--rule", required=True)
    p.add_argument("--scope", default="all")
    p.add_argument("--source")
    p = sub.add_parser("supersede")
    p.add_argument("gid")
    p.add_argument("--rule", required=True)
    p.add_argument("--scope")
    p = sub.add_parser("rules")
    p.add_argument("--json", action="store_true")
    sub.add_parser("tick")
    p = sub.add_parser("candidates")
    p.add_argument("--min-runs", type=int, default=2)
    p = sub.add_parser("promoted")
    p.add_argument("gids", nargs="+")
    args = ap.parse_args()
    data = load()
    {
        "init": cmd_init, "ask": cmd_ask, "open": cmd_open, "answer": cmd_answer,
        "add-rule": cmd_add_rule, "supersede": cmd_supersede, "rules": cmd_rules,
        "tick": cmd_tick, "candidates": cmd_candidates, "promoted": cmd_promoted,
    }[args.cmd](args, data)


if __name__ == "__main__":
    main()
